# Generated by Django 5.2.1 on 2025-05-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('category_info', models.TextField(max_length=500)),
            ],
            options={
                'verbose_name': 'Ads Category',
                'verbose_name_plural': 'Ads Categories',
                'db_table': 'ads_category',
            },
        ),
        migrations.CreateModel(
            name='Advertiser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(blank=True, max_length=250, null=True)),
                ('ad_description', models.TextField(blank=True, max_length=500, null=True)),
                ('ad_image', models.ImageField(blank=True, null=True, upload_to='adsImage/%Y/%m/%d/')),
                ('ad_condition', models.CharField(blank=True, choices=[('new', 'New'), ('used', 'Used'), ('old', 'Old')], max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ad_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_ads.adscategory')),
                ('user_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Advertiser',
                'verbose_name_plural': 'Advertisers',
                'db_table': 'advertiser',
            },
        ),
    ]
