# Generated by Django 5.2.1 on 2025-06-01 17:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertiser',
            name='target_ad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_offers', to='app_ads.advertiser'),
        ),
    ]
